### ISSUE TITLE
Mega base blueprint and naming

### ISSUE THREAD

**Issue by nyurik** [bcwhite-code/brians-blueprints#1]
Hi, thanks for all the hard work of the blueprints! Do you also plan to add the [mega factory](https://www.factorio.school/view/-MNZWdWosuqr3vtaC2hD) here too? I would like to propose some minor naming cleanups, but wasn't sure where you keep the sources. Thanks!

**Comment by bcwhite-code** [comment]
They're in the "self-building-factory" subdirectory.

-- Brian
(sent from my Android; expect typos and brevity)
