### ISSUE TITLE
SpaceEx- Loader station in mall having issues

### ISSUE THREAD

**Issue by alepocalypse** [bcwhite-code/brians-blueprints#11]
Freshly stamped mall + home. the blue requestor chest on the SUPPLY stop is requesting 1 of every item. so it is just filling the merged loader chest with tons of garbage.

**Comment by bcwhite-code** [comment]
It's not the mall.  You have a problem with a circuit network somewhere in the factory that is feeding bad requests to the mall's Supply station logic.  You'll likely see some kind of constant signals on the train grid's green wire instead of cycling fully between the 10 channels.
