### ISSUE TITLE
Self-Building Rocket Feedback

### ISSUE THREAD

**Issue by ptarjan** [bcwhite-code/brians-blueprints#12]
Thanks so much for building this! I did a full run through and collected some feedback incase you want to do some minor updates. Thanks again for doing such an amazing job with your Factorio blueprints. https://docs.google.com/document/d/1li0WxDM-rTtZi8wdVpgZqgdiYsLZXbYJdo-8K6AR9Kg/edit?usp=sharing

I used V1.2.0 from https://factorioprints.com/view/-MGvN8qrxpCMbXJJn3Gh

* General
    * I LOVE how most of the power poles tile at the right distance. Thank you thank you.
    * Give recommendations to put down in order: belts, then power, then assemblers, then inserters. The belts automatically stay in line when you run, the power nicely tiles as you run, the assemblers are a bigger deal if they are mis-placed and the inserters can be seen to be working if they are last
    * Tell the user to queue the science research from bottom to top
    * Maybe include some radar to help find ore patches to go after
    * Adding personal roboport and personal battery before the yellow science gets going is a good quality of life change
    * The name of the blue-print of “Self-Building Rocket” didn’t really speak to me since I had to do much of the work. Maybe “Self-Contained Rocket” or “Speed-Building Rocket”.
* Step 0
    * The “Initial Stone Mining” box should be limited to 2 stacks
* Step 2
    * Green science seems to be the bottleneck later on, which in turn is bottlenecked on the iron plates. Maybe enlarge that to start since you’re already asking for us to run many lines of iron ore?
* Step 4
    * Errant blue inserter near the top green circuit maker
    * Including an upgrade from assembler 1 to assembler 2 and stone furnace to steel furnace
    * The long horizontal lines of pipes just south of the oil refineries for water and oil make it hard to walk. Maybe underground it?
* Step 5
    * There are some extraneous small electric poles in the plastic area
    * Extraneous passive provider chests by the steel furnace and 2 by the the robot constructor
* Step 6
    * Inconsistent placement of the constant combinator for the iron
    * The construction area for the southern most roboport doesn't cover 2 squares of the blueprint on the input lines to the iron
    * The power belt blueprint should
        * Have water inputs every 32 slots
        * Be as bigger to accommodate 32*3 engines
    * The underground belt feeding the green circuits to the construction robot maker changed from Step 5 breaking all production of robots
    * Suggest that we hand-craft some medium electric poles and put them in the bin incase the build order doesn’t have the robots making them early enough
* Step 7
    * The robot frame construction seems to have shut off waiting on a green circuit reading that isn’t coming in
    * I like the simplicity of your input lines but serially running ores into them made the factory not as productive as I expected. Could you extend the blueprint leftword and collate the inputs with balancers so that if I haven’t ran the 9 copper belts in yet, the yellow science isn’t fully blocked?
    * I seemed to have needed more power than you said
    * Maybe have a cargo box for the fish?
* General
    * Use a small amount of X, Y snapping to more easily re-align the blueprint. 5 on both X and Y were great for me
    * The 36 power blueprint
        * Should connect the power poles and the water lines
        * Should have inputs for the water at the right places and ratios
    * Suggest to run a dedicated coal line into each 36 power plant instead of siphoning off other coal lines

Amazing job! I loved the play-through.

**Comment by bcwhite-code** [comment]
>
> General
>
> I LOVE how most of the power poles tile at the right distance. Thank you
> thank you.
> Give recommendations to put down in order: belts, then power, then
> assemblers, then inserters. The belts automatically stay in line when you
> run, the power nicely tiles as you run, the assemblers are a bigger deal if
> they are mis-placed and the inserters can be seen to be working if they are
> last
>
Noted.


> Tell the user to queue the science research from bottom to top
> Maybe include some radar to help find ore patches to go after
> Adding personal roboport and personal battery before the yellow science
> gets going is a good quality of life change
>
Noted.


> The name of the blue-print of “Self-Building Rocket” didn’t really speak
> to me since I had to do much of the work. Maybe “Self-Contained Rocket” or
> “Speed-Building Rocket”.
> Step 0
> The “Initial Stone Mining” box should be limited to 2 stacks
>
Done.


> Step 2
> Green science seems to be the bottleneck later on, which in turn is
> bottlenecked on the iron plates. Maybe enlarge that to start since you’re
> already asking for us to run many lines of iron ore?
>
Too big of a change.


> Step 4
> Errant blue inserter near the top green circuit maker
>
Removed.


> Including an upgrade from assembler 1 to assembler 2 and stone furnace to
> steel furnace
>
Done.


> The long horizontal lines of pipes just south of the oil refineries for
> water and oil make it hard to walk. Maybe underground it?
>
Done.



> Step 5
> There are some extraneous small electric poles in the plastic area
>
Found 1.  Removed.


> Extraneous passive provider chests by the steel furnace and 2 by the the
> robot constructor
>
Not extraneous.  It can take a while before PPCs are made available to the
bots but the stuff put in those chests is somewhat urgent.


> Step 6
> Inconsistent placement of the constant combinator for the iron
>
Moved.


> The construction area for the southern most roboport doesn't cover 2
> squares of the blueprint on the input lines to the iron
>
Ghost belts removed.



> The power belt blueprint should
> Have water inputs every 32 slots
> Be as bigger to accommodate 32*3 engines
>
One steam engine consumes 30 steam per second, and one offshore pump
produces 1200 water per second, so each offshore pump produces enough water
to supply 40 steam engines.  Blueprint is 36 per input pipe.


> The underground belt feeding the green circuits to the construction robot
> maker changed from Step 5 breaking all production of robots
>
Fixed.


> Suggest that we hand-craft some medium electric poles and put them in the
> bin incase the build order doesn’t have the robots making them early enough
>
Noted.


> Step 7
> The robot frame construction seems to have shut off waiting on a green
> circuit reading that isn’t coming in
>
Probably due to the badly placed underground-belt exit in step #5.


> I like the simplicity of your input lines but serially running ores into
> them made the factory not as productive as I expected. Could you extend the
> blueprint leftword and collate the inputs with balancers so that if I
> haven’t ran the 9 copper belts in yet, the yellow science isn’t fully
> blocked?
>
No, but I added a note in the instructions to do one copper belt for each
factory, then the iron, then the remaining copper.  That should accomplish
about the same.


> I seemed to have needed more power than you said
>
Worst-case isn't average or even typical.


> Maybe have a cargo box for the fish?
> General
> Use a small amount of X, Y snapping to more easily re-align the blueprint.
> 5 on both X and Y were great for me
>
Great idea!  Done.


> The 36 power blueprint
> Should connect the power poles and the water lines
>
Power connected.  Water has to be separate pipes.


> Should have inputs for the water at the right places and ratios
> Suggest to run a dedicated coal line into each 36 power plant instead of
> siphoning off other coal lines
>
Noted.


> Amazing job! I loved the play-through.
>
Glad you liked it.

**Comment by bcwhite-code** [comment]
v1.3.0 released on [Factorio Prints](https://factorioprints.com/view/-MGvN8qrxpCMbXJJn3Gh).
