### ISSUE TITLE
load/Unload station smaller footprint

### ISSUE THREAD

**Issue by Ringkeeper** [bcwhite-code/brians-blueprints#20]
Thank you for the blueprints.

Would it be possible to offer also a loader/unload station with a smaller footprint similar to the LTN ones in the chunk-alligned books?

https://factorioprints.com/view/-M-gLfVHJstwMyNzr044
https://imgur.com/L0MyeMJ

Stations can unload to the front or back and have smaller footprint, which is quite good if you need multiple next to each other

**Comment by bcwhite-code** [comment]
For small footprint, use the "merged" station bodies and the load/unload prints for them.  Much smaller with higher throughput and less load on UPS.
